apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - repo: https://helm.cilium.io/
    name: cilium
    releaseName: cilium
    namespace: kube-system
    version: 1.18.2
    valuesFile: values.yaml
~                                
