apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmCharts:
  - repo: https://charts.longhorn.io
    name: longhorn
    releaseName: longhorn
    namespace: longhorn-system
    version: 1.10.1
    valuesFile: values.yaml
