apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

helmCharts:
  - repo: https://prometheus-community.github.io/helm-charts
    name: prometheus
    releaseName: prometheus
    namespace: prometheus
    version: v3.7.1
    valuesFile: values.yaml
