apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: grafana
    releaseName: grafana
    namespace: grafana
    version: 10.1.2
    valuesFile: values.yaml
