apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

helmCharts:
  - repo: https://github.com/grafana/helm-charts
    name: grafana
    releaseName: grafana
    namespace: grafana
    version: 12.2.0
    valuesFile: values.yaml
