apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- argocd-ingress.yaml

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure="true"
  - server.disable.auth="true"

- name: argocd-cm
  behavior: merge
  literals:
  - kustomize.buildOptions: --enable-helm
  files:
  - resource.customizations
