apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-monitoring

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: k8s-monitoring
    releaseName: k8s-monitoring
    namespace: k8s-monitoring
    version: 3.5.2
    valuesFile: values.yaml
