cluster:
  name: "monitoring"

destinations: 
  - name: loki
    type: loki
    url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

clusterEvents:
  enabled: true
  collector: alloy-logs
nodeLogs:
  enabled: true
podLogs:
  enabled: true
podLogsViaKubernetesApi:
  enabled: true

alloy-logs:
  enabled: true
  alloy:
    clustering:
      enabled: true
